### ISSUE TITLE
Error trying to call a 0-arg function

### ISSUE THREAD

**Issue by Pietro222222** [nonamescm/yex-lang#21]
```
yex> let a = (fn = 2)
>> nil
yex> a()
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', vm/src/lib.rs:154:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_bounds_check
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:76:5
   3: vm::VirtualMachine::run
   4: vm::VirtualMachine::run
   5: yex::start
   6: yex::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by nonamescm** [comment]
this is a problem with the REPL. Not with the function itself.
